# Generated by Django 6.0.2 on 2026-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_is_special_case_student_special_case_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
