# Generated by Django 6.0.2 on 2026-03-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_revised', to='students.bus'),
        ),
    ]
