# Generated by Django 6.0.2 on 2026-03-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_student_bus_id_alter_student_bus_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('bus_number', 'academic_year')},
        ),
    ]
