# Generated by Django 6.0.2 on 2026-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_bus_options_bus_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
