# Generated by Django 6.0.2 on 2026-03-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolsettings_installed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='trial_days',
            field=models.IntegerField(default=15),
        ),
    ]
