# Generated by Django 6.0.2 on 2026-03-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schoolsettings_trial_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
