# Generated by Django 6.0.2 on 2026-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_academicyear_options_academicyear_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_stop',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
