# Generated by Django 6.0.2 on 2026-03-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='bus_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.bus'),
        ),
    ]
