# Generated by Django 6.0.2 on 2026-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='trial_days',
            field=models.IntegerField(default=10),
        ),
    ]
